import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { AuthProvider } from '@/contexts/AuthContext';
import { InvestmentProvider } from '@/contexts/InvestmentContext';
import { NavBar } from '@/components/NavBar';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-linear-to-br from-gray-50 to-gray-100 min-h-screen flex flex-col`}
      >
        <AuthProvider>
          <InvestmentProvider>
            <NavBar />

            <main className="flex-1">{children}</main>

            {/* Footer */}
            <footer className="bg-white shadow-md">
              <div className="container mx-auto px-4 py-6 text-center text-gray-600">
                <p>
                  &copy; 2025 Meus Investimentos. Todos os direitos reservados.
                </p>
              </div>
            </footer>
          </InvestmentProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
